# name: Deploy 
# on: [push]
# jobs: 
#   Update Resume Gist:
#     uses: exuanbo/actions-deploy-gist@v1
#     with:
#       token: ${{ secrets.TOKEN }}
#       gist_id: 1245e5ad3fd46aab94507fe03366b16d
#       file_path: ./resume.json
#       file_type: text
#       gist_description: "Zack McKenna's JSON resume"

name: hello-world

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World! again!"
